#!/usr/bin/env python

#   Rounder - Poker for the GNOME Desktop
#
#   Copyright (C) 2006 Devan Goodwin <dgoodwin@dangerouslyinc.com>
#   Copyright (C) 2006 James Bowes <jbowes@dangerouslyinc.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301  USA

"""
Thin script to run rounder from the source directory. (and not the installed
version)
"""

import sys
sys.path.insert(0, './src/')

from rounder.log import setup_logging
import logging

# Configure logging: (needs to be done before importing our modules)
log_conf_locations = ["./logging.conf"]
setup_logging(log_conf_locations)

from rounder.ui.gtk.main import RounderGtk

if __name__ == "__main__":
    rounderApp = RounderGtk()
    rounderApp.main()

